#pragma once
#ifndef GAME_FORCED_INCLUDE_H
#define GAME_FORCED_INCLUDE_H

#define WARP_PHYSICS_MODIFIER 1.333333333f

#define PACKET_HEALTH_UPDATE_FREQUENCY 0.5
#define PHYSICS_PACKET_TIMER_LIMIT 0.25
#define SERVER_CLIENT_TIMEOUT 20.0f
#define SERVER_CLIENT_RECOVERY_TIME 60.0f

#endif